#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jaxen
Version  : 1.1.1.final
Release  : 1
URL      : https://github.com/codehaus/jaxen/archive/V1_1_1_Final.tar.gz
Source0  : https://github.com/codehaus/jaxen/archive/V1_1_1_Final.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-jaxen-license = %{version}-%{release}

%description
No detailed description available

%package license
Summary: license components for the mvn-jaxen package.
Group: Default

%description license
license components for the mvn-jaxen package.


%prep
%setup -q -n jaxen-1_1_1_Final

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jaxen
cp jaxen/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-jaxen/jaxen_LICENSE.txt

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jaxen/jaxen_LICENSE.txt
