#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jaxen
Version  : 1.1.1.final
Release  : 2
URL      : https://github.com/codehaus/jaxen/archive/V1_1_1_Final.tar.gz
Source0  : https://github.com/codehaus/jaxen/archive/V1_1_1_Final.tar.gz
Source1  : https://repo1.maven.org/maven2/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar
Source2  : https://repo1.maven.org/maven2/jaxen/jaxen/1.1.1/jaxen-1.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-jaxen-data = %{version}-%{release}
Requires: mvn-jaxen-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jaxen package.
Group: Data

%description data
data components for the mvn-jaxen package.


%package license
Summary: license components for the mvn-jaxen package.
Group: Default

%description license
license components for the mvn-jaxen package.


%prep
%setup -q -n jaxen-1_1_1_Final

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jaxen
cp jaxen/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-jaxen/jaxen_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/jaxen/jaxen/1.1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jaxen/jaxen/1.1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.jar
/usr/share/java/.m2/repository/jaxen/jaxen/1.1.1/jaxen-1.1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jaxen/jaxen_LICENSE.txt
